apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    zone: prod
    version: v1
    project: catgif
    application: catv1
spec:
  containers:
    - name: example-ctr
      image: gursimran2407murthy/catgif:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 5000

        